site_name: My Docs
site_url: https://example.com/
theme:
  name: material
  palette:
    scheme: slate
    primary: blue
    accent: deep purple
  font: Noto Sans JP
  features:
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
plugins:
  - search
